language: node_js
node_js:
    - "node"
before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.2
    - export PATH="$HOME/.yarn/bin:$PATH"
cache:
    yarn: true
script:
    - ./.travis-runner.sh
env:
 - CXX=g++-5
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - g++-5
